plugins { id 'net.neoforged.moddev' }

def neoVersion = '26.2.0.59'

repositories {
    maven { url = 'https://maven.neoforged.net/releases' }
}

neoForge {
    version = neoVersion

    runs {
        client { client() }
    }

    mods {
        chatmanager_core { sourceSet sourceSets.main }
    }
}

dependencies {
    jarJar(implementation("com.ferra13671:mega-events")) {
        version {
            strictly '[1.7.1,2.0)'
            prefer '1.7.1'
        }
    }
    implementation "me.shedaniel.cloth:cloth-config-neoforge:26.2.155"
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}
tasks.withType(JavaCompile).configureEach { options.release = 25 }

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/neoforge.mods.toml') { expand version: project.version }
}