modLoader = "lowcodefml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/SakaPati/ChatManager-Core/issues"
license = "GPL-3.0"

[[mods]]
modId = "chatmanager_core"
version = "${version}"
displayName = "ChatManager-Core"
authors = "Fozeton"
description = '''
ChatManager-Core is a library for working with Minecraft chat
'''
logoFile = "assets/chatmanager_core/icon.png"

[[dependencies.chatmanager_core]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chatmanager_core]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4]"
ordering = "NONE"
side = "BOTH"

[[dependencies.chatmanager_core]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "chatmanager_core.mixins.json"